version: "3.8"

name: festo-dt

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: festo-api
    env_file:
      - ./api/.env
    ports:
      - "8000:8000"
    restart: unless-stopped
    command: ["uvicorn","api.api_ws:app","--host","0.0.0.0","--port","8000"]
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://127.0.0.1:8000/health || exit 1"]
      interval: 30s
      timeout: 3s
      retries: 3
